services:
  - type: web
    name: sign-language-detector
    env: python
    plan: free
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    build:
      aptDependencies:
        - libavformat-dev
        - libavcodec-dev
        - libavdevice-dev
        - libavutil-dev
        - libavfilter-dev
        - libswscale-dev
        - libswresample-dev